@host = http://localhost:5000
@notification_id = 69a5a5f35-19d4-49a5-8081-a341c2138d98

###
GET {{host}}/v1/api/notification/{{notification_id}}


###
POST {{host}}/v1/api/notification
Content-Type: application/json

{
    "user_id": "00000000-0000-0000-0000-000000000001",
    "message": "This is a test notification",
    "notification_type": 1
}