@host = http://localhost:5000
@notification_id = a0c4fe5e-15fa-4d24-ac52-99dc2e4ea797

###
GET {{host}}/v1/api/notification/{{notification_id}}


###
POST {{host}}/v1/api/notification
Content-Type: application/json

{
    "user_id": "00000000-0000-0000-0000-000000000001",
    "message": "This is a test notification",
    "notification_type": 1
}