// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/quangnguyen1505/go-notification-system/global/noti"
	"github.com/quangnguyen1505/go-notification-system/internal/notification/app/router"
	"github.com/quangnguyen1505/go-notification-system/internal/notification/infras/repo"
	"github.com/quangnguyen1505/go-notification-system/internal/notification/usecases/notification"
	"github.com/quangnguyen1505/go-notification-system/pkg/postgres"
	"google.golang.org/grpc"
)

// Injectors from wire.go:

func InitApp(grpcServer *grpc.Server) (*App, func(), error) {
	dbEngine, cleanup, err := dbEngineFunc()
	if err != nil {
		return nil, nil, err
	}
	notificationRepo := repo.NewNotificationRepo(dbEngine)
	service := notification.NewService(notificationRepo)
	notificationServiceServer := router.NewNotificationGRPCServer(grpcServer, service)
	app := New(dbEngine, notificationServiceServer)
	return app, func() {
		cleanup()
	}, nil
}

// wire.go:

func dbEngineFunc() (postgres.DBEngine, func(), error) {
	db, err := postgres.NewPostgresDB(&noti.Config.Postgres, noti.Logger)
	if err != nil {
		return nil, nil, err
	}
	return db, func() { db.Close() }, nil
}
