// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/quangnguyen1505/go-notification-system/cmd/notification/config"
	"github.com/quangnguyen1505/go-notification-system/internal/notification/app/router"
	"github.com/quangnguyen1505/go-notification-system/internal/notification/infras/repo"
	"github.com/quangnguyen1505/go-notification-system/internal/notification/usecases/notification"
	"github.com/quangnguyen1505/go-notification-system/pkg/logger"
	"github.com/quangnguyen1505/go-notification-system/pkg/postgres"
	"google.golang.org/grpc"
)

// Injectors from wire.go:

func InitApp(cfg *config.Config, logger2 *logger.LoggerZap, grpcServer *grpc.Server) (*App, func(), error) {
	dbEngine, cleanup, err := dbEngineFunc(cfg, logger2)
	if err != nil {
		return nil, nil, err
	}
	notificationRepo := repo.NewNotificationRepo(dbEngine, logger2)
	service := notification.NewService(notificationRepo, logger2)
	notificationServiceServer := router.NewNotificationGRPCServer(grpcServer, service)
	app := New(cfg, logger2, dbEngine, notificationServiceServer)
	return app, func() {
		cleanup()
	}, nil
}

// wire.go:

func dbEngineFunc(config2 *config.Config, logger2 *logger.LoggerZap) (postgres.DBEngine, func(), error) {
	db, err := postgres.NewPostgresDB(&config2.Postgres, logger2)
	if err != nil {
		return nil, nil, err
	}
	return db, func() { db.Close() }, nil
}
